# Generated by Django 6.0.4 on 2026-04-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_description_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from client', null=True),
        ),
    ]
