# Generated by Django 6.0.4 on 2026-05-01 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_blogpost_notes_contactmessage_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='navigationitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='amount_paid',
            new_name='mpesa_amount',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin delivery notes', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_link',
            field=models.URLField(blank=True, help_text='Link to completed work', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_content',
            field=models.TextField(default='We are a creative agency dedicated to bringing your vision to life.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_document',
            field=models.FileField(blank=True, null=True, upload_to='about_docs/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(default='About Original Grand Productions', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='custom_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='client_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
