# Generated by Django 6.0.4 on 2026-05-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_portfolioitem'),
    ]

    operations = [
    ]
